- name: This is a simple test playbook
  hosts: all
  gather_facts: False
  vars:
    ansible_user: SVC_Remote@uncc.edu
    ansible_password: Bell@0916!
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_become: false
    ansible_winrm_scheme: https
  tasks:
    - name: run ipconfig
      raw: ipconfig
      register: ipconfig
    - debug: var=ipconfig
