---

# Add Cisco Amp Repo RHEL 7
- name: Add Cisco Amp Repo (RHEL 7)
  shell: subscription-manager attach --pool 188fa8436276f2e401628792b94c01fa
  when: ansible_distribution_major_version == "7"
  ignore_errors: yes  
  tags: ciscoamp

# Add Cisco Amp Repo RHEL 7
- name: Add Cisco Amp Repo (RHEL 6)
  shell: subscription-manager attach --pool 188fa8436276f2e401628790d56d01f2
  when: ansible_distribution_major_version == "6"
  ignore_errors: yes
  tags: ciscoamp

# Use yum localinstall to install the Satellite CA RPMs
- name: yum install the Cisco Amp Agent
  yum: name=ciscoampconnector state=latest
  tags: ciscoamp

# Start service
- name: Start cisco-amp
  shell: systemctl start cisco-amp
  tags: ciscoamp

# Set cisco amp to start on boot
- name: Enable cisco-amp
  shell: systemctl enable cisco-amp
  tags: ciscoamp

